"""empty message

Revision ID: ccadd8dee772
Revises: de746311f1fc
Create Date: 2022-04-09 03:51:03.572466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccadd8dee772'
down_revision = 'de746311f1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_account_id_key', 'user_account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_account_id_key', 'user_account', ['id'])
    # ### end Alembic commands ###
