"""empty message

Revision ID: de746311f1fc
Revises: 29cce4b8b66b
Create Date: 2022-04-09 03:32:59.460654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de746311f1fc'
down_revision = '29cce4b8b66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'test')
    # ### end Alembic commands ###
